repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.12.0
    hooks:
      - id: isort

  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.17.5
    hooks:
      - id: pylint
        args: [--disable=C0114,C0115,C0116]  # Disable missing docstring warnings if you want
